# Generated by Django 5.1.4 on 2025-01-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='data',
            new_name='date',
        ),
    ]
